apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: client-build
spec:
  source:
    git:
      uri: https://github.com/rayenchtioui/microservices-base
    contextDir: services/client
  strategy:
    dockerStrategy:
      dockerfilePath: services/client/DockerFile
  output:
    to:
      kind: ImageStreamTag
      name: client:latest
