apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: email-template
objects:
- kind: ImageStream
  apiVersion: v1
  metadata:
    name: email
    labels:
      app: email
  spec:
    lookupPolicy:
      local: false
- kind: BuildConfig
  apiVersion: v1
  metadata:
    name: email
    labels:
      app: email
  spec:
    runPolicy: Serial
    triggers:
    - type: GitHub
      github:
        secret: secret101
    - type: Generic
      generic:
        secret: secret101
    - type: ImageChange
    source:
      git:
        uri: "https://github.com/rayenchtioui/microservices-base"
    strategy:
      type: Docker
      dockerStrategy:
        dockerfilePath: services/email/Dockerfile
    output:
      to:
        kind: ImageStreamTag
        name: email:latest
- kind: DeploymentConfig
  apiVersion: v1
  metadata:
    name: email
    labels:
      app: email
  spec:
    replicas: 1
    selector:
      app: email
    template:
      metadata:
        labels:
          app: email
      spec:
        containers:
        - name: email
          image: email:latest
          imagePullPolicy: Always
          ports:
          - containerPort: 8000
          envFrom:
          - secretRef:
              name: email-secret
          env:
          - name: RUN_ENV
            value: OpenShift-With-Dockerfile
    triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
        - email
        from:
          kind: ImageStreamTag
          name: email:latest
- kind: Service
  apiVersion: v1
  metadata:
    name: email
    labels:
      app: email
  spec:
    ports:
    - name: http
      port: 8000
      targetPort: 8000
    selector:
      app: email
    type: ClusterIP
- kind: Route
  apiVersion: route.openshift.io/v1
  metadata:
    name: email
    labels:
      app: email
  spec:
    to:
      kind: Service
      name: email
    port:
      targetPort: http
