apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: user-template
objects:
- kind: ImageStream
  apiVersion: v1
  metadata:
    annotations:
    labels:
      app: user
    name: user
  spec:
    lookupPolicy:
      local: false
- kind: "BuildConfig"
  apiVersion: "v1"
  metadata:
    name: "user" 
    labels:
      app: user
  spec:
    runPolicy: "Serial" 
    triggers: 
      -
        type: "GitHub"
        github:
          secret: "secret101"
      - type: "Generic"
        generic:
          secret: "secret101"
      -
        type: "ImageChange"
    source: 
      git:
        uri: "https://github.com/rayenchtioui/microservices-base"
    strategy:
      type: Docker
      dockerStrategy:
        dockerfilePath: services/user/Dockerfile       
    output: 
      to:
        kind: "ImageStreamTag"
        name: "user:latest"
- kind: "DeploymentConfig"
  apiVersion: "v1"
  metadata:
    name: "user"
    labels:
      app: user
  spec:
    template: 
      metadata:
        labels:
          name: "user"
          app: user
      spec:
        containers:
          - name: "user"
            imagePullPolicy: Always
            ports:
              - containerPort: 8080
                protocol: "TCP"
            envFrom:
          - secretRef:
              name: user-secret
            env:
              - name: RUN_ENV
                value: OpenShift-With-Dockerfile 
        restartPolicy: Always
    replicas: 1 
    triggers:
      - type: "ConfigChange" 
      - type: "ImageChange" 
        imageChangeParams:
          automatic: true
          containerNames:
            - "user"
          from:
            kind: "ImageStreamTag"
            name: "user:latest"
    strategy: 
      type: "Rolling"
    paused: false 
    revisionHistoryLimit: 2 
    minReadySeconds: 0 
- kind: Service
  apiVersion: v1
  metadata:
    annotations:
    name: user
    labels:
      app: user
  spec:
    ports:
    - name: 8080-tcp
      protocol: TCP
      port: 8080
      targetPort: 8080
    selector:
      app: user
    type: ClusterIP
    sessionAffinity: None
- kind: Route
  apiVersion: route.openshift.io/v1
  metadata:
    name: user
    labels:
      app: user
    annotations:
  spec:
    to:
      kind: Service
      name: user
      weight: 100
    port:
      targetPort: 8080-tcp
  wildcardPolicy: None  
