name: Run Unit Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Test Service 1
      run: |
        cd services/client
        npm install
        npx jest
        cd ..
        cd ..

    - name: Test Service 2
      run: |
        cd services/product
        npm install
        npx jest
        cd ..
        cd ..

    - name: Test Service 3
      run: |
        cd services/user
        npm install
        npx jest
        cd ..
        cd ..
    